### ISSUE TITLE
Stopped working for me?

### ISSUE THREAD

**Issue by reihinomars** [rawxbee/neoboard-enhancement-suite#13]
So I was using this in Firefox yesterday and it worked fine but when I turned on my macbook this morning, it wasn't working anymore. I do have other scripts but none that do anything similar. (The only one for the boards is my neotagger.)

**Comment by moonbathr** [comment]
@reihinomars Are you still running into this issue? If so, have you tried updating the script in question? Redownloading from the source is the best way. If it persists, do you mind sharing the URL of the page you're on? Occasionally, the issue is just that the URL doesn't perfectly match the ones the script is intended to run on, which should be a simple fix.

**Comment by reihinomars** [comment]
I had to rulling uninstall and redownload the script in question to fix the problem actually. I tried updating it, turning it off for a bit, neither worked. I feel like it was updating my browser (firefox) and then reinstalling that fixed it.

**Comment by moonbathr** [comment]
Awesome - glad it worked! Will recommend that to folks in the future if they run into the same issue on FF/Mac 👍
